parameters:
- name: serviceName
  type: string
- name: dockerfilePath
  type: string

jobs:
- job: Build_${{ parameters.serviceName }}
  displayName: Build and Push ${{ parameters.serviceName }}
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Docker@2
    displayName: Build and Push to ACR
    inputs:
      containerRegistry: '$(dockerRegistryServiceConnection)'
      repository: '${{ parameters.serviceName }}'
      command: 'buildAndPush'
      Dockerfile: '${{ parameters.dockerfilePath }}'
      tags: |
        $(Build.BuildId)
        latest
